version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://user:user@127.0.0.1/micro-post
          MAILER_FROM: micro@micropost.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'user'
          MYSQL_DATABASE: 'micro-post'
    steps:
      - checkout
      - run:
          name: Install Sodium Library
          command: |
            sudo git clone https://github.com/jedisct1/libsodium --branch stable && cd libsodium && sudo ./configure && sudo make && sudo make check && sudo make install
      - run:
          name: Install zlib
          command: sudo apt-get install libzip-dev
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-configure zip --with-libzip && sudo docker-php-ext-install pdo_mysql sodium zip
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction